### ISSUE TITLE
Accessing DTO mappers

### ISSUE THREAD

**Issue by ConnorJBishop** [JonPSmith/EfCore.GenericServices.AspNetCore#6]
This is question about EfCore.GenericServices and EfCore.GenericBizRunner but in the context of ASP NET Core app so Im asking here.

Let's say I have a Post endpoint which takes in a `CreateTodoDto` model, similar to the example, but instead of returning a CreatedAt response with a `TodoItem`result, I want to return a `TodoItemDto` model as an abstraction over the database entity. 

I changed the `ICreateTodoBizLogic` to return a `TodoItemDto`, however I find myself having to manually build the DTO to be returned. How can I take advantage of the fact that I have used `ILinkToEntity<TodoItem>` and access the mapper that has already been setup?

In a similar vein, how can I take advantage of `CreateTodoDto` being linked to `TodoItem` to automatically populate properties of `TodoItem` rather than building from scratch inside the `BizAction` method?

Hope this makes sense, thanks in advance for your response.

**Comment by JonPSmith** [comment]
Hi @ConnorJBishop,

Let me answer your questions:

>  I want to return a TodoItemDto model... can I access the mapper that has already been setup?

Yes, you can access the mapper that the `ILinkToEntity<TodoItem>` sets up. There is a class called `WrappedConfigAndMapper` in the `PublicBuHidden` folder that contains two properties called `MapperReadConfig` and `MapperSaveConfig` that contains the AutoMapper mappings. The `WrappedConfigAndMapper` class is registered as a singleton, so you can obtain an instance of that class to access the mappings.

I use this to map a entity class to a DTO using `...ProjectTo<TDto>(_wrappedMapper.MapperReadConfig)`. See the internal class called [CreateMapper](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/Internal/MappingCode/CreateMapper.cs) and look at the following methods:

- `GetViaKeysWithProject`
- `ProjectAndThenApplyWhereExpression`
- `GetManyProjectedNoTracking`

_NOTE: The code is complex because I'm working with dynamic class types. Your code will be much simpler_.

>  use CreateTodoDto being linked to TodoItem to automatically populate properties of TodoItem

Yes by using the `MapperSaveConfig` mappings. I use this to map a DTO onto an entity class using `_wrappedMapper.MapperSaveConfig.CreateMapper().Map(dto, entity)`. You also can find this in the [CreateMapper](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/Internal/MappingCode/CreateMapper.cs) in the method called `MapDtoToEntity`

I hope that helps you.
